import { createFileRoute } from "@tanstack/react-router";
import { Callout } from "../components/Callout";
import { CodeBlock } from "../components/CodeBlock";
import { TopicLayout } from "../components/TopicLayout";

export const Route = createFileRoute("/ci-cd")({
	component: Page,
});

function Page() {
	return (
		<TopicLayout
			slug="/ci-cd"
			group="Workspace"
			title="CI with GitHub Actions"
			tagline="A GitHub Actions workflow that runs typecheck, lint, tests, and builds on every PR. Fail-fast, cache-aware, fast on the second run."
		>
			<p>
				Continuous integration (CI) is the green checkmark that says "this PR didn't
				obviously break anything". The minimum we want on every push:
			</p>
			<ol>
				<li>Install dependencies (cached).</li>
				<li>Generate code that's normally generated by Vite/protoc.</li>
				<li>Type-check.</li>
				<li>Lint and format-check.</li>
				<li>Run unit tests.</li>
				<li>Build.</li>
			</ol>
			<p>
				Each step depends on the previous. If typecheck fails, no point running tests.
				That's <strong>fail-fast</strong>.
			</p>

			<h2>The minimum viable workflow</h2>
			<CodeBlock lang="yaml" filename=".github/workflows/ci.yml">{`name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel in-flight runs on the same branch so a new push wins.
concurrency:
  group: ci-\${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history so turbo --filter can diff

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Generate proto types
        run: pnpm run proto:generate

      - name: Typecheck
        run: pnpm exec turbo run typecheck

      - name: Lint
        run: pnpm exec turbo run lint

      - name: Test
        run: pnpm exec turbo run test

      - name: Build
        run: pnpm exec turbo run build`}</CodeBlock>

			<h2>What each piece does</h2>
			<table>
				<thead><tr><th>Block</th><th>Why</th></tr></thead>
				<tbody>
					<tr><td><code>concurrency</code></td><td>If you push twice quickly, only the latest run keeps going. Saves CI minutes.</td></tr>
					<tr><td><code>fetch-depth: 0</code></td><td>Need full git history for turbo's <code>--filter=...[origin/main]</code> to diff.</td></tr>
					<tr><td><code>cache: pnpm</code></td><td>Caches the pnpm store. Second run installs in seconds.</td></tr>
					<tr><td><code>--frozen-lockfile</code></td><td>Refuse to update <code>pnpm-lock.yaml</code>. CI installs exactly what was committed.</td></tr>
					<tr><td><code>timeout-minutes</code></td><td>Cap a hung run. 15 minutes is generous for most repos.</td></tr>
				</tbody>
			</table>

			<h2>Caching turbo's output</h2>
			<p>
				Turborepo has its own cache (<code>.turbo</code>). Persist it across CI runs to
				make the second run essentially free for unchanged packages:
			</p>
			<CodeBlock lang="yaml">{`- uses: actions/cache@v4
  with:
    path: .turbo
    key: turbo-\${{ runner.os }}-\${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}-\${{ github.sha }}
    restore-keys: |
      turbo-\${{ runner.os }}-\${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}-
      turbo-\${{ runner.os }}-`}</CodeBlock>

			<h2>Filtering on PRs</h2>
			<p>
				When the PR only touched one package, you don't need to validate everything.
				Turborepo's git-aware filter scopes work to changed packages and their
				dependents.
			</p>
			<CodeBlock lang="yaml">{`- name: Set turbo filter
  id: filter
  run: |
    if [ "\${{ github.event_name }}" = "pull_request" ]; then
      echo "filter=--filter=...[origin/\${{ github.base_ref }}]" >> "$GITHUB_OUTPUT"
    else
      echo "filter=" >> "$GITHUB_OUTPUT"
    fi

- name: Typecheck
  run: pnpm exec turbo run typecheck \${{ steps.filter.outputs.filter }}`}</CodeBlock>

			<h2>Three traps to avoid</h2>
			<ul>
				<li>
					<strong>Generated files not in git, not in CI</strong>: if a file is
					generated by Vite at dev time and gitignored, CI's <code>tsc</code> won't
					see it. Either commit the generated file or generate it explicitly in CI.
				</li>
				<li>
					<strong>Tests that pass locally but fail in CI</strong>: usually a
					timezone, locale, or env difference. Pin <code>TZ=UTC</code> in the
					workflow if your code touches dates.
				</li>
				<li>
					<strong>Secrets in workflow files</strong>: never put real secrets in YAML.
					Use GitHub repository secrets and reference as <code>$&#123;&#123; secrets.NAME &#125;&#125;</code>.
				</li>
			</ul>

			<h2>Required status checks</h2>
			<p>
				A workflow that runs on PRs is only useful if PRs can't be merged when it
				fails. In repository settings, enable branch protection on <code>main</code>:
			</p>
			<ul>
				<li>Require pull request reviews before merging.</li>
				<li>Require the <code>validate</code> job to pass.</li>
				<li>Require branches to be up to date before merging.</li>
			</ul>

			<Callout kind="tip" title="Start with one job">
				<p>
					Don't split into "lint" / "test" / "build" jobs from the start. One job
					that runs them in sequence is easier to read, and turbo + cache make it
					almost as fast. Split only when one step is much slower than the others
					and could parallelise.
				</p>
			</Callout>

			<h2>Common interview questions</h2>
			<ul>
				<li>
					<strong>What's the difference between CI and CD?</strong> CI is "validate
					this change". CD is "deploy this change". They are usually different
					workflows: CI on every PR, CD on merge to main.
				</li>
				<li>
					<strong>Why fail-fast in CI?</strong> Save minutes and developer time. If
					typecheck fails, no point running the slower tests.
				</li>
				<li>
					<strong>Why <code>--frozen-lockfile</code>?</strong> CI must install exactly
					what was committed. Without the flag, pnpm/npm might silently bump versions
					to satisfy the manifest, breaking reproducibility.
				</li>
				<li>
					<strong>How do you make CI fast on the second run?</strong> Cache the
					package manager store, cache turbo's output, scope work to changed packages
					on PRs.
				</li>
			</ul>
		</TopicLayout>
	);
}
